---

  - block:
      - name: Get vector distrib
        ansible.builtin.get_url:
          url: "https://packages.timber.io/vector/{{vector_version}}/{{ item }}-{{ vector_version }}-1.x86_64.rpm"
          dest: "./{{ item }}-{{ vector_version }}.rpm"
        with_items: "{{ vector_packages }}"
        # https://packages.timber.io/vector/0.22.3/vector-0.22.3-1.x86_64.rpm
  - name: Install vector package
    become: true
    ansible.builtin.yum:
      name:
        - vector-{{ vector_version }}.rpm
      state: present
  - name: Vector | Template config    
    ansible.builtin.template:
      src: vector.yml.j2
      dest: vector.yml
      mode: "0644"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"
      validate: vector validate --no-environment --config-yaml %s
  - name: vector | create unit
    become: true
    ansible.builtin.template:
      src: vector.service.j2
      dest: /etc/systemd/system/vector.service
      mode: "0644"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"
  - name: vector | start sevice
    ansible.builtin.systemd:
      name: vector
      state: started
      enabled: yes
      daemon_reload: yes 
  # - name: Ensure vector is running
  #   ansible.builtin.service:
  #     name: vector
  #     state: started
